services:
  tigi-mssql-box:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - tigi-mssql-box.env
    ports:
      - 1433:1433
    volumes:
      - tigi-mssql-box-vol:/var/opt/mssql
volumes:
  tigi-mssql-box-vol:
    external: true
